// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlTtth6UmyIE6gUrCsTL6BL4bvp-xKIA8',
    appId: '1:1056259043893:web:ac4effec9d191510b4777c',
    messagingSenderId: '1056259043893',
    projectId: 'dentalclinicapp-9f1d1',
    authDomain: 'dentalclinicapp-9f1d1.firebaseapp.com',
    storageBucket: 'dentalclinicapp-9f1d1.firebasestorage.app',
    measurementId: 'G-83C21147XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAnCM4nVd2-1A2JDt0DFQgjzvsH1CnGIg',
    appId: '1:1056259043893:android:4d5bfd5eb5b4ee40b4777c',
    messagingSenderId: '1056259043893',
    projectId: 'dentalclinicapp-9f1d1',
    storageBucket: 'dentalclinicapp-9f1d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsZZp4puvlqf-7GbqdlWc-B2-PpByEp4',
    appId: '1:1056259043893:ios:b3611e3c96afd9aeb4777c',
    messagingSenderId: '1056259043893',
    projectId: 'dentalclinicapp-9f1d1',
    storageBucket: 'dentalclinicapp-9f1d1.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSsZZp4puvlqf-7GbqdlWc-B2-PpByEp4',
    appId: '1:1056259043893:ios:b3611e3c96afd9aeb4777c',
    messagingSenderId: '1056259043893',
    projectId: 'dentalclinicapp-9f1d1',
    storageBucket: 'dentalclinicapp-9f1d1.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlTtth6UmyIE6gUrCsTL6BL4bvp-xKIA8',
    appId: '1:1056259043893:web:ac4effec9d191510b4777c',
    messagingSenderId: '1056259043893',
    projectId: 'dentalclinicapp-9f1d1',
    authDomain: 'dentalclinicapp-9f1d1.firebaseapp.com',
    storageBucket: 'dentalclinicapp-9f1d1.firebasestorage.app',
    measurementId: 'G-83C21147XJ',
  );

}
